### PR TITLE
fix building with libxml 2.12.0

### PR DESCRIPTION
**Pull request by raveit65**
```
gvc-sound-theme-chooser.c:462:15: error: implicit declaration of function ‘xmlParseFile’; did you mean ‘xmlSaveFile’? [-Werror=implicit-function-declaration]
462 |         doc = xmlParseFile (filename);
|               ^~~~~~~~~~~~
|               xmlSaveFile
gvc-sound-theme-chooser.c:462:13: warning: assignment to ‘xmlDocPtr’ {aka ‘struct _xmlDoc *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
462 |         doc = xmlParseFile (filename);
|             ^
```
Successful build with libxml-2.12.0 from fedora-rawhide at fedora build-server https://koji.fedoraproject.org/koji/taskinfo?taskID=109500185
https://src.fedoraproject.org/rpms/mate-media/blob/rawhide/f/mate-media.spec#_14

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
Like the others,, this builds clean and generates no runtimes surprises, sound theme chooser worked same as before. Test was with libxml2.9 not 2.12 but no issues
