### PR TITLE
Add MPRIS media controls to the volume applet and status icon

### PR DESCRIPTION
**Pull request by KeremSoke**
## Summary

This PR adds MPRIS media-player integration to both the MATE volume applet and the standalone status icon.

The main goal is to expose MPRIS playback controls from the existing volume UI, without requiring a separate media-control applet.

This includes:

- MPRIS player discovery and tracking over D-Bus
- a shared backend for player metadata, playback state, and transport controls
- a reusable player widget for cover art, track information, seeking, and playback actions
- applet integration
- status icon integration following the applet behavior as closely as possible
- new settings/schema entries for media-related behavior
- Meson/build updates, including an in-process/Wayland-related applet fix

## Motivation

The volume applet and status icon already serve as persistent audio-control surfaces, so MPRIS playback control fits the same interaction model.

With this change, users can:

- view the active media player directly from the volume UI
- see track information and player identity
- control playback without opening the player window
- switch between available players
- seek within tracks
- use mouse and touchpad shortcuts directly on the icon
- access player-related actions from the right-click menu

The feature is additive: the existing volume workflow remains the same when no MPRIS-compatible player is running. And you can disable the whole show media player feature can be disabled. 

## Implementation overview

The work is split into several layers.

### 1. Build and settings plumbing

This PR adds:

- Meson wiring for the new MPRIS-related sources
- `gio` / `gio-unix` dependencies required by the player integration
- a new `org.mate.volume-control` schema for media/player-related settings
- an in-process applet metadata/build fix needed while testing the applet path, especially in Wayland sessions

### 2. MPRIS backend

Two internal components were added:

- `GvcMprisManager`
  - discovers and tracks MPRIS players on the session bus
  - listens for player appearance/removal
  - exposes available players
  - selects a best active player

- `GvcMprisPlayer`
  - represents one MPRIS player
  - tracks metadata, playback status, capabilities, and transport state
  - exposes play/pause, next, previous, stop, raise, quit, and seek actions

This keeps D-Bus/MPRIS logic separate from the UI layer.

### 3. Shared player widget

A reusable `GvcPlayerWidget` was added for the popup UI.

It provides:

- player selection when multiple players are available
- title/artist display
- cover art
- playback controls
- repeat/shuffle controls
- seek bar and time display

The widget is shared between the applet and status icon to avoid duplicating the player UI implementation.

### 4. Applet integration

The applet implementation came first and acts as the reference path for the feature.

The applet now:

- tracks active MPRIS players
- embeds the shared player widget in the popup
- can show track text in the panel
- can include player information in tooltips
- supports player-aware middle-click behavior
- supports extra mouse buttons for previous/next track
- supports horizontal touchpad/scroll gestures on the icon for previous/next track
- adds player-related actions and selection in the right-click menu

### 5. Status icon integration

After the applet path was working, I ported the same behavior to the standalone status icon as closely as practical.

The status icon now:

- uses the same MPRIS backend
- reuses the same shared player widget
- exposes player metadata and controls in its popup
- follows the same settings-driven behavior where practical

The intent is to keep the applet and status icon behavior aligned instead of maintaining two unrelated implementations.

## Interaction improvements

In addition to popup controls, this PR adds direct interaction paths:

- configurable middle-click behavior for media control
- extra mouse buttons for previous/next track
- horizontal touchpad/scroll gestures on the icon for previous/next track
- player actions exposed through the right-click menu

This keeps common playback actions available without opening the full player UI.

## Player compatibility

This PR includes compatibility handling inspired by Cinnamon's MPRIS behavior to improve real-world player matching and launch behavior, including Spotify-style desktop integration cases.

## Related input-stream fix

While testing this area, I also adjusted input-stream visibility so recording activity is detected more reliably across input streams, not only the default input stream.

This is separate from MPRIS but included because it affects the same status/applet UI surface.

## Settings added

This PR adds settings for:

- showing track text in the panel
- showing player controls
- middle-click behavior
- horizontal scroll media control behavior
- known player tracking
- tooltip volume visibility
- tooltip player visibility

These settings make the feature configurable rather than forcing one media-control workflow for all users.

## Testing

I tested this manually in a Wayland session.

Verified:

- the applet works in a Wayland session
- in my testing, the applet behaves the same there as it does in an X session
- popup behavior works
- MPRIS player detection works
- media controls work
- player metadata is shown
- the status icon path works after porting the applet behavior across
- existing volume-control behavior remains available

## Review notes

The implementation order was:

1. build/settings groundwork
2. shared MPRIS backend
3. shared player widget
4. applet integration
5. status icon integration

The status icon work is intentionally derived from the applet path rather than being a separate design.

## Why this fits in mate-media

This feature extends the existing audio-control UI instead of adding a separate media-control surface.

It uses the standard MPRIS D-Bus interface, keeps the player logic modular, shares UI between the applet and status icon, preserves the existing volume-control behavior, and was tested in Wayland with the applet behaving the same as it does in an X session.

### CODE REVIEW

**Comment by L-U-T-i** [comment]
Build on RHEL 9.8 (`glib2-devel-2.68.4-19.el9_8.1.x86_64`) fails with a bunch of `undefined reference to gvc_mpris_...` and `undefined reference to gvc_player_...` errors.

**Comment by raveit65** [comment]
I really like this PR because i use my box as an oldschool multimedia personal computer.
But it is imposible to build it on actual fedora OS.
Any chance to start working on it again?
